spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@dongheemonitor.osabdyy.mongodb.net/DongHeeMonitor?retryWrites=true&w=majority&appName=DongHeeMonitor

github:
  token: ${DONGHEE_MONITOR_GITHUB_TOKEN}
  commit-url: https://api.github.com/repos/xpmxf4/jjapterpark-frontend/commits

slack:
  signing-secret: ${SLACK_SIGNING_SECRET}
  bot-token: ${SLACK_BOT_TOKEN}
  app-token: ${SLACK_APP_TOKEN}
  donghee-id: U06QKHUF9MK

riot:
  api-key: ${RIOT_API_KEY}
  donghee-puuid: aOCeMo0I2IkAXt19RhWEo_eoy6rP6CjUlhHWsRtzm0X2eJgCEqLBXWgQxQlWOxrlFlSyncmvaeiOkA
